name: PolarSouls
version: 1.0.0
main: com.mario.polarsouls.PolarSouls
api-version: '1.21'
author: Mario
description: Hardcore lives system with cross-server Limbo exile and revival mechanics

commands:
  revive:
    description: Revive a dead player and return them from Limbo
    usage: /revive <player>
    permission: polarsouls.revive
    permission-message: "&cYou don't have permission to revive players."

  setlimbospawn:
    description: Set the Limbo spawn location to your current position
    usage: /setlimbospawn
    permission: polarsouls.admin
    permission-message: "&cYou don't have permission to use this command."

  pstatus:
    description: Check a player's hardcore status (lives, death state)
    usage: /pstatus [player]
    permission: polarsouls.status
    permission-message: "&cYou don't have permission to use this command."

  psetlives:
    description: Set a player's life count
    usage: /psetlives <player> <lives>
    permission: polarsouls.admin
    permission-message: "&cYou don't have permission to use this command."

  psadmin:
    description: PolarSouls admin commands
    usage: /psadmin <subcommand> [args]
    aliases: [psa]
    permission: polarsouls.admin
    permission-message: "&cYou don't have permission to use this command."

  limbo:
    description: Visit the Limbo world as a living player
    usage: /limbo
    aliases: [visitlimbo]
    permission: polarsouls.visit
    permission-message: "&cYou don't have permission to visit Limbo."

  leavelimbo:
    description: Leave Limbo and return to Main (visitors only)
    usage: /leavelimbo
    aliases: [hub]
    permission: polarsouls.visit
    permission-message: "&cYou don't have permission to use this command."

permissions:
  polarsouls.revive:
    description: Allows reviving dead players
    default: op

  polarsouls.admin:
    description: Full admin access to PolarSouls
    default: op

  polarsouls.status:
    description: Check player status
    default: true

  polarsouls.visit:
    description: Allows visiting Limbo as a living player
    default: true

  polarsouls.bypass:
    description: Bypass all death and limbo mechanics
    default: false
